spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatty
    username: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    root: info

jwt-secret-key: FC6363F38DF714CFE1C697E24EB75S23S23AM2MF4LMI1DUM3
jwt-access-token-expiration-time: 10000
jwt-refresh-token-expiration-time: 300000

naver-cloud-sms-access-key: EfLYwq7WXi11Bc0DHKTS
naver-cloud-sms-secret-key: 1xMmLBEhPcW8rB4vWL0atjHkBDqGMxsZ3egFsGw9
naver-cloud-sms-service-id: ncp:sms:kr:322059361753:chatty_sms
naver-cloud-sms-sender-phone-number: 01062585055

redis-token-host: localhost
redis-authenticationNumber-host: localhost
redis-port: 6379